version: '3.8'

services:
  frontend:
    image: your_custom_frontend_image
    networks:
      - frontend_network
    depends_on:
      - backend

  backend:
    image: your_custom_backend_image
    command: node server.js
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - database
    environment:
      DB_HOST: database

  database:
    image: your_custom_database_image
    networks:
      - backend_network
    environment:
      POSTGRES_PASSWORD: testpsswd

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
